language: scala
sudo: false

addons:
  postgresql: 9.4
  mariadb: 10.0

before_script:
  - psql -U postgres -c 'create database travis_ci_test;'
  - mysql -e 'create database travis_ci_test;'

matrix:
  include:
    - scala: 2.11.5
      jdk: oraclejdk8
